spring:
  jpa:
    show-sql: false
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${FIAPBOOK_POSTGRES_URL}
    username: ${FIAPBOOK_POSTGRES_USERNAME}
    password: ${FIAPBOOK_POSTGRES_PASSWORD}
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

server:
  port: 8080

api:
  security:
    token:
      secret: ${FIAPBOOK_API_SECURITY_TOKEN_SECRET}